language: node_js

node_js:
  - "node"
  - "7"
  - "6"

env:
  global:
    - GENERATE_COVERAGE=1

  matrix:
    - CI_BROWSER=ChromeHeadless
    - CI_BROWSER=PhantomJS

addons:
  chrome: stable

cache:
  yarn: true
  directories:
    - node_modules

after_success:
  - 'if [ "$TRAVIS_PULL_REQUEST = "false" ]; then cat build/coverage/xml/lcov.info | node_modules/.bin/coveralls; fi'
