language: node_js

node_js:
  - "node"
  - "7"
  - "6"

addons:
  chrome: stable

cache:
  yarn: true
  directories:
    - node_modules

script:
  - yarn run test-ci

# TODO: Test against multiple browsers
