language: node_js

node_js:
  - "node"
  - "7"
  - "6"

env:
  global:
    - GENERATE_COVERAGE=1

  matrix:
    - CI_BROWSER=ChromeHeadless
    - CI_BROWSER=PhantomJS

addons:
  chrome: stable

cache:
  yarn: true
  directories:
    - node_modules
